#第一和是运行的环境
run: 'DEVIP'
hosts:
  DEVIP:
    # DEV_IP配置
    MS_USER: 'http://192.168.62.253:31012'
    MS_PASSPORT: 'http://192.168.62.253:31007'
    MS_ORDER: 'http://192.168.62.253:31003'
    MS_PAY: 'https://dev.ms.pay.sjnc.com'
    MS_CHECKER: 'http://192.168.62.253:31023'
    MS_CART: 'http://192.168.62.253:31014'
    MS_SHOP: 'http://192.168.62.253:31009'
    MS_PRODUCT: 'http://192.168.62.253:31005'
    MS_KBMS: 'http://192.168.62.253:31020'
    MS_PLANT: 'http://192.168.62.253:31029'
    MS_SCHEDULER: 'http://192.168.62.253:31025'
    MS_SEARCH: 'http://192.168.62.253:31027'
  DEV:
    # DEV域名配置
    MS_USER: 'http://dev.ms.user.sjnc.com'
    MS_PASSPORT: 'http://dev.ms.passport.sjnc.com'
    MS_ORDER: 'http://dev.ms.order.sjnc.com'
    MS_PAY: 'https://dev.ms.pay.sjnc.com'
    MS_CHECKER: 'http://dev.ms.checker.sjnc.com'
    MS_CART: 'http://dev.ms.cart.sjnc.com'
    MS_SHOP: 'http://dev.ms.shop.sjnc.com'
    MS_PRODUCT: 'http://dev.ms.product.sjnc.com'
    MS_KBMS: 'http://dev.ms.kbms.sjnc.com'
    MS_MESSAGE: 'http://dev.ms.message.sjnc.com'
    MS_PLANT: 'http://dev.ms.plant.sjnc.com'
    MS_SCHEDULER: 'http://dev.ms.scheduler.sjnc.com'
    MS_SEARCH: 'http://dev.ms.search.sjnc.com'
    #   QA域名配置
  QA:
    MS_USER: 'http://qa.ms.user.sjnc.com'
    MS_PASSPORT: 'http://qa.ms.passport.sjnc.com'
    MS_ORDER: 'http://qa.ms.order.sjnc.com'
    MS_PAY: 'http://qa.ms.pay.sjnc.com'
    MS_CHECKER: 'http://qa.ms.checker.sjnc.com'
    MS_CART: 'http://qa.ms.cart.sjnc.com'
    MS_SHOP: 'http://qa.ms.shop.sjnc.com'
    MS_PRODUCT: 'http://qa.ms.product.sjnc.com'
    MS_KBMS: 'http://qa.ms.kbms.sjnc.com'
    MS_MESSAGE: 'http://qa.ms.message.sjnc.com'
    MS_PLANT: 'http://qa.ms.plant.sjnc.com'
    MS_SCHEDULER: 'http://qa.ms.scheduler.sjnc.com'
    MS_SEARCH: 'http://qa.ms.search.sjnc.com'
detabase:
  QA:
    host_ip: '132.232.47.119'
  DEV:
    host_ip: '39.104.28.40'
  DEVIP:
    host_ip: '39.104.28.40'
User:
  QA:
    op:
      account: '007'
      password: '123456'
  DEV:
    op:
      account: '18919028888'
      password: '123456'
  DEVIP:
    op:
      account: '18328433208'
      password: '123456'